{% set name = "ezsheets" %}
{% set version = "2024.8.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/EZSheets-{{ version }}.tar.gz
  sha256: 9c5a3b76fb73209ddff79bf2090e14f16dc851198c7be2184d5c1f393191ce90

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4
    - google-api-python-client
    - google-auth-oauthlib
    - oauth2client

test:
  imports:
    - ezsheets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/asweigart/ezsheets
  summary: A Pythonic interface to the Google Sheets API that actually works as of August 2021.
  license: GPL-3.0-or-later
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
